version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "german-tools"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1phuo2s8ximw1"
s3_prefix = "german-tools"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
